[package]
name = "shh"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "shh"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
inquire = "0.7"
anyhow = "1"
thiserror = "1"
security-framework = { version = "3", features = ["OSX_10_15"] }
shellexpand = "3"
